spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:3306/forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.POSTGRESQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
